iad_filer_tech:
    channels:
        local:
            adapter: local
            enable_public: true
            enable_private: true
            public_path: "%filer_channel_local_public_path%"
            private_path: "%filer_channel_local_private_path%"

#    picture_filer:
#        channel: local
#        public_base_url: "%picture_filer.base_url%"
#        resizing_filters: []

#    document_filer:
#        channel: local

liip_imagine:
    driver: imagick
    filter_sets:
        high:
            quality: 90
            filters:
                thumbnail: { size: [800, 600], mode: inset }

        medium:
            quality: 90
            filters:
                thumbnail: { size: [300, 300], mode: inset }

        small:
            quality: 80
            filters:
                thumbnail: { size: [170, 170], mode: inset }

        tiny:
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: inset }

        watermark:
            filters:
                watermark:
                    image: ../vendor/iad-holding/filer-tech-bundle/Iad/Bundle/FilerTechBundle/Resources/Data/watermark.png
                    size: 0.5
                    position: bottomright
