iad_filer_document_download:
    path: /documents/download/{uuid}
    defaults: { _controller: IadFilerTechBundle:Filer:getDocument }
    methods: GET
    requirements:
        uuid: "[a-zA-Z0-9-]+"

iad_sponsorship_filer_rest:
    prefix:   /filer
    resource: "@IadFilerTechBundle/Resources/config/rest_routing.yml"
    type:     rest
